### ISSUE TITLE
Outputting currently resolved artifact to console

### ISSUE THREAD

**Issue by petroseskinder** [bazelbuild/migration-tooling#2]
This is a simple aesthetic change. It would be nice if generate_workspace could output what artifact it is currently resolving. For example:
```
INFO: Running command line: //generate_workspace '--maven_project=/helloworld' '--artifact=org.powermock:powermock-module-junit4:1.5.1' '--artifact=org.powermock:powermock-api-mockito:1.5.1'
    ...
    Resolving model org.powermock powermock-module-junit4 1.5.1
    Resolving model org.powermock powermock-modules 1.5.1
    Resolving model org.powermock powermock 1.5.1
    Resolving model org.sonatype.oss oss-parent 5
    Resolving model junit junit 4.11
    Resolving model org.hamcrest hamcrest-core 1.3
    Resolving model org.hamcrest hamcrest-parent 1.3
    Resolving model org.powermock powermock-module-junit4-common 1.5.1
    Resolving model org.powermock powermock-modules 1.5.1
    Resolving model org.powermock powermock 1.5.1
    Resolving model org.sonatype.oss oss-parent 5
```
@kchodorow, how would you like it to output the currently resolved artifact? In addition, when there are duplicates, do you want it to skip over those duplicates?

**Comment by kchodorow** [comment]
> @kchodorow, how would you like it to output the currently resolved artifact? 

I think it only needs to print the artifact identifier it's currently downloading.  Downloading is the only thing that should take any time.

> In addition, when there are duplicates, do you want it to skip over those duplicates?

If you only print when downloads happen, duplicates shouldn't be an issue.

Also, as a personal preference: I'd rather see the artifact in Maven coordinate form (group:artifact:version) and it would be nice to include who requested it, if it's not too gnarly.

**Comment by petroseskinder** [comment]
That should not be problem. Thanks for the clarification.
