### ISSUE TITLE
Zip Release

### ISSUE THREAD

**Issue by cpenner-va** [bazelbuild/migration-tooling#26]
Thanks for all your work on this! I'm wondering if we could get a tagged release; specifically I'd like to include the project via bazel's `http_archive` rule, but I need a released zip file for this. Thanks!

**Comment by kchodorow** [comment]
You can actually get a zip for any commit (e.g., https://github.com/bazelbuild/migration-tooling/archive/1e2ef5948247998a714fc75acae30fe6ca7ede6b.zip), but that's kind of gross, I'll try to cut a release today.

**Comment by kchodorow** [comment]
Cut https://github.com/bazelbuild/migration-tooling/releases/tag/0.0.1, you can use https://github.com/bazelbuild/migration-tooling/archive/0.0.1.zip.

**Comment by cpenner-va** [comment]
Thanks! 🎉
