### ISSUE TITLE
generate_workspace may pull in too much from dependencyManagement section of POMs

### ISSUE THREAD

**Issue by greggdonovan** [bazelbuild/migration-tooling#43]
Running `bazel run //generate_workspace -- '--artifact=org.apache.beam:beam-sdks-java-core:2.0.0'` took >1hr and generated a >100k bzl file.

If I remove the JARs pulled in via the [parent POMs `dependencyManagement`](https://github.com/bazelbuild/migration-tooling/blob/master/generate_workspace/src/main/java/com/google/devtools/build/workspace/maven/Resolver.java#L210:L216), the result appears reasonable.

Should `generate_workspace` pull in every dependency specified in the full set of parent POMs or just use their versions to override the child POMs versions? Or should only a certain set of JARs brought in through dependencyManagement be used?

**Comment by petroseskinder** [comment]
This issue is being solved here #44.

**Comment by petroseskinder** [comment]
@kchodorow can you close this as well?

**Comment by kchodorow** [comment]
Fixes by #44.
