### ISSUE TITLE
Support dependencyManagement sections within Maven

### ISSUE THREAD

**Issue by petroseskinder** [bazelbuild/migration-tooling#8]
# Migrating from [issue 307](https://github.com/bazelbuild/bazel/issues/307) in main repository
See https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/bazel-dev/CuGGIbMnuYM/fGzfSY1CjOsJ

**Comment by petroseskinder** [comment]
@kchodorow this should be reopened.

**Comment by kchodorow** [comment]
I think the issues are covered by #41.
